language: shell

os:
  - windows
  - osx
  - linux

script:
  - source .travis/java.sh
  - .travis/jdde.sh
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

apfter_success:
  - ls -lah target/packages/ target/bundles/

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Svetlozar Argirov"
  - git config --local user.email "zarrro@gmail.com"
  - export TRAVIS_TAG=3.0.0
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - target/packages/*
    - target/bundles/*
  skip_cleanup: true
  draft: true
  on:
    branch: travis-ci